#!/bin/bash

mkdir 0x06-python-classes

cd 0x06-python-classes



echo "<>" > 0-square.py

echo "<>" > 1-square.py

echo "<>" > 101-square.py

echo "<>" > 102-square.py

echo "<>" > 103-square.py

echo "<>" > 2-square.py

echo "<>" > 3-square.py

echo "<>" > 4-square.py

echo "<>" > 5-square.py

echo "<>" > 6-square.py

echo "Python Classes and Objects" > README.md



git add .

git commit -m "more update"

git push


